### ISSUE TITLE
FieUser.cs could not be found.

### ISSUE THREAD

**Issue by Alexiril** [FriendshipIsEpic/FiE-Game#1]
Hello.
I was trying to build the project, downloaded the assets and the sources. Both JetBrains Rider and Visual Studio (2022) said there's no FieUser.cs (src/Fie.User/FieUser.cs) file in the project. There are no Scenes folder (and scenes themselves) in the assets, so it's not possible to build. By the way, there are no meta files in the assets, but I guess they are not the most important for building.

Can you please upload the files (if you have them, of course)? It would be so great!

![image](https://github.com/FriendshipIsEpic/FiE-Game/assets/96677511/f1cd603d-33cf-4fd6-9313-9f3176ec27f6)

**Comment by Sollace** [comment]
I'll see what I can do. The project is not really buildable in its current state, though. As you noticed, there are no scenes.

What's there is as much as I was able to extract from the dev build but I never got far enough to try building it.

**Comment by Alexiril** [comment]
Okay, thanks for the answer, now I understand why there are no meta files nor scenes :)

**Comment by Sollace** [comment]
The project should look a little better now.

**Comment by Alexiril** [comment]
Wow, thanks a lot! It looks like 200% cooler now! I tried to do it myself, but not so successfully.
