### ISSUE TITLE
Identify and add prerequisite libraries and plugins

### ISSUE THREAD

**Issue by Sollace** [FriendshipIsEpic/FiE-Game#3]
The original project was created using a long list of extra unity plugins, that if we can't find them we'd have to rewrite portions of the codebase to work without.

Thanks to @Alexiril 's efforts, we have a rough idea of what plugins are missing/were used, so this issue is here to keep track of them and what we know so far.

- [x] ParticlePlayground ([v1 - discontinued](https://forum.unity.com/threads/particle-playground-framework-for-controlling-particles.203361/)) ([current - paid](https://forum.unity.com/threads/particle-playground.215154/))
- [x] Cinema Director
- [x] HighlightingSystem ([paid](https://forum.unity.com/threads/highlighting-system-released.143043/))
- [x] PigeonCoopToolkit.Effect.Trails ~~( [Touch Input Manager - paid](https://forum.unity.com/threads/touch-input-manager-must-have-for-joysticks-and-buttons.262421/) )~~ ([free](https://github.com/11one/PanzerWar/tree/5b4a1aca70805143099df773c3c945acc898229c/Assets/ExtraPlugins/TrailEffect))
- [x] RogoDigital.Lipsync ~~([Lipsync Pro - paid](https://www.rogodigital.com/))~~ ([free](https://github.com/Rtyper/LipSync-Pro))
- [x] [CircularGravityForce](https://unityassetcollection.com/circular-gravity-force-free-download/) ~~([paid](https://assetstore.unity.com/packages/tools/particles-effects/circular-gravity-force-8181))~~ ([free](https://github.com/ahnafnafee/NeedForABC/tree/92dc2153825aec27ef62f2b254f04279737731d0/Assets/Imported/ResurgamStudios/CircularGravityForce%20Package))
- [x] TMPro ([TexMesh Pro - free](https://forum.unity.com/threads/useful-information-download-links.458634/#post-3304434)) 
- [x] Spine.Unity / Spine ([free](https://esotericsoftware.com/spine-unity-download/)) (version 3.5 for unity 5.4-2017 (based on date)?)
- [x] Colorful FX
- [x] Rewired.UI.ControlMapper
- [x] PopcornFX
- [x] QuickRopes Rope Physics (no idea what namespace)
- [x] ~~WULogin (MBS namespace?)~~

**Comment by Sollace** [comment]
PigeonCoopToolkit appears to be [Touch Input Manager](https://forum.unity.com/threads/touch-input-manager-must-have-for-joysticks-and-buttons.262421/) by a user named Pigeon Coop. Code for it happens to be on github [here](https://github.com/houshuo/wzry/tree/master/CSharp-firstpass/PigeonCoopToolkit) (though not sure if functional)

**Comment by Sollace** [comment]
RogoDigital.Lipsync appears to be [these guys](https://www.rogodigital.com/)

**Comment by Sollace** [comment]
Found a usable copy of PigeonToolkip.Effect.Trails: https://github.com/11one/PanzerWar/tree/5b4a1aca70805143099df773c3c945acc898229c/Assets/ExtraPlugins/TrailEffect

And CircularGravityForce here: https://github.com/ahnafnafee/NeedForABC/tree/92dc2153825aec27ef62f2b254f04279737731d0/Assets/Imported/ResurgamStudios/CircularGravityForce%20Package

And LibSync Pro is open source (no need to go through the assets store or scrape from unity projects): https://github.com/Rtyper/LipSync-Pro

**Comment by Sollace** [comment]
Let me know @Alexiril if any of this is useful

**Comment by Alexiril** [comment]
Sure, I am checking them all out :)

**Comment by Alexiril** [comment]
Hi again :)
While I was analyzing the files again, I found out some other packages I don't have and couldn't find:

- **Rewired.UI.ControlMapper**
- **QuickRopes Rope Physics (no idea what namespace)**
- **WULogin (MBS namespace?)**

All of them are probably paid (not sure, though), and some (like quickropes) are no longer distributed.

**Comment by Alexiril** [comment]
By the way, Spine is done, so it can be checked :)

**Comment by Alexiril** [comment]
Hi again! CinemaDirector, Colorful, TMPro are done :)

**Comment by Alexiril** [comment]
I have to mention that Particle Playground, Highlighting System, Rewired, PopcornFX are done.

**There are only 20 errors left in all game files, a couple of weeks ago there were about 500-600, it's a great progress :)**

**Comment by Sollace** [comment]
Woo! Nice!

At this rate we'll soon be able to start testing

**Comment by Alexiril** [comment]
We are close to try to build it! No more errors left in the code. Quick Ropes are done. Unfortunately, WordPress for Unity (MBSCore) with WUlogin costs around $500. I couldn't find a free version. Technically, we don't need that package until we will try to start a web server and play online again :)

**Comment by Sollace** [comment]
Awesome! Everything's done, so I can close this now
